-- PSTO Zambales DATABASE — Supabase schema. Run once in the Supabase SQL Editor.
-- After running, follow README step 3 to create the first administrator.

-- ============ helpers (created after profiles) ============
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  name text not null,
  role text not null default 'Staff' check (role in ('Administrator','Staff','Guest')),
  active boolean not null default true,
  must_change_password boolean not null default true,
  personnel_scope_all boolean not null default false,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as
$$ select exists(select 1 from profiles where id=auth.uid() and role='Administrator' and active) $$;

create or replace function public.my_role() returns text language sql stable security definer set search_path=public as
$$ select role from profiles where id=auth.uid() and active $$;

create or replace function public.has_perm(tab text, act text) returns boolean language sql stable security definer set search_path=public as
$$ select public.is_admin() or coalesce((select (permissions->tab->>act)::boolean from profiles where id=auth.uid() and active),false) $$;

-- ============ tables ============
create table public.personnel (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete set null,
  first_name text, middle_name text, last_name text, suffix text, name text,
  position text, employee_id text, birthdate date,
  employment_status text, employment_status_other text,
  department text, home_address text,
  phones text[] default '{}', emails text[] default '{}',
  status text default 'Active', color text default '#2563eb',
  call_card_qr text, headshot text, notes text,
  created_at timestamptz default now()
);
create or replace function public.can_manage_person(pid bigint) returns boolean language sql stable security definer set search_path=public as
$$ select public.is_admin() or (public.my_role()='Staff' and (
     exists(select 1 from profiles where id=auth.uid() and personnel_scope_all)
     or exists(select 1 from personnel where id=pid and user_id=auth.uid()))) $$;

create table public.personnel_documents (
  id bigint generated by default as identity primary key,
  personnel_id bigint not null references personnel(id) on delete cascade,
  name text, doc_date date, year text, has_link boolean default false, notes text,
  files jsonb default '[]', added_by uuid default auth.uid(), created_at timestamptz default now()
);
-- document links are private to the owner + admin, so they live in their own table
create table public.personnel_doc_links (
  doc_id bigint primary key references personnel_documents(id) on delete cascade,
  link text
);
create table public.attendance (
  id bigint generated by default as identity primary key,
  date date, employee text, status text, time_in time, time_out time, remarks text,
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.leave_records (
  id bigint generated by default as identity primary key,
  employee text, type text, other_type text, date_from date, date_to date, days numeric,
  status text default 'Pending', remarks text, files jsonb default '[]',
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.calendar_events (
  id bigint generated by default as identity primary key,
  title text, category text, other_category text, start_date date, end_date date,
  time time, venue text, person_ids bigint[] default '{}', remarks text, files jsonb default '[]',
  linked_leave_id bigint unique references leave_records(id) on delete cascade,
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.contacts (
  id bigint generated by default as identity primary key,
  name text, designation text, department text, municipality text, phone text, email text,
  date_acquired date, remarks text,
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.memos (
  id bigint generated by default as identity primary key,
  memo_number text, date date, subject text, program text, program_other text, sent date,
  remarks text, files jsonb default '[]',
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.trainings (
  id bigint generated by default as identity primary key,
  title text, participants bigint[] default '{}', conducted_by text, duration text,
  date_from date, date_to date, amount numeric, funding text, certificate text, remarks text,
  files jsonb default '[]',
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.email_records (
  id bigint generated by default as identity primary key,
  date date, direction text, from_to text, subject text, assigned_to text, program text,
  reference text, status text, remarks text, files jsonb default '[]',
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.documentation (
  id bigint generated by default as identity primary key,
  direction text default 'Incoming', date_received date, doc_type text, reference_no text,
  from_to text, title text, action text, remarks text, files jsonb default '[]',
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.doc_types (name text primary key);
create table public.funds (
  id bigint generated by default as identity primary key,
  fund_type text, entry_type text, date date, person_id bigint, party text, amount numeric,
  description text, remarks text,
  added_by uuid default auth.uid(), added_by_name text, created_at timestamptz default now()
);
create table public.fund_types (name text primary key);
create table public.focal_items (
  id bigint generated by default as identity primary key,
  section text not null check (section in ('programs','linkages','tasks')),
  title text not null, focal text, alternate text,
  added_by uuid default auth.uid(), created_at timestamptz default now()
);
create table public.qr_codes (
  id bigint generated by default as identity primary key,
  label text, real_image text, real_link text, decoy_image text, decoy_link text
);
create table public.audit_log (
  id bigint generated by default as identity primary key,
  at timestamptz default now(), user_id uuid, user_name text, action text, section text, detail text
);
create table public.trash (
  id bigint generated by default as identity primary key,
  type text, deleted_at timestamptz default now(), deleted_by text, record jsonb
);
create table public.settings (key text primary key, value jsonb);

insert into doc_types values ('Communication Letter'),('Newsletter'),('Memo'),('Reminder'),('Request'),('Report'),('Other');
insert into fund_types values ('General Office Fund');
insert into settings values ('emailOverdueDays','3');

-- ============ triggers ============
create or replace function public.personnel_set_name() returns trigger language plpgsql as $$
begin
  new.name := coalesce(nullif(trim(concat_ws(' ',nullif(new.first_name,''),nullif(new.middle_name,''),nullif(new.last_name,''),nullif(new.suffix,''))),''), new.name, '');
  return new;
end $$;
create trigger trg_personnel_name before insert or update on personnel for each row execute function personnel_set_name();

-- when a personnel name changes, keep name-based references consistent
create or replace function public.personnel_rename_cascade() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if old.name is distinct from new.name and coalesce(old.name,'')<>'' then
    update attendance set employee=new.name where employee=old.name;
    update leave_records set employee=new.name where employee=old.name;
    update email_records set assigned_to=new.name where assigned_to=old.name;
    update focal_items set focal=new.name where focal=old.name;
    update focal_items set alternate=new.name where alternate=old.name;
    update calendar_events set title=new.name||substr(title,length(old.name)+1) where left(title,length(old.name)+3)=old.name||' — ';
  end if;
  return new;
end $$;
create trigger trg_personnel_rename after update on personnel for each row execute function personnel_rename_cascade();

-- approved leave automatically appears on the calendar
create or replace function public.sync_leave_calendar() returns trigger language plpgsql security definer set search_path=public as $$
declare pid bigint; lbl text; ed date;
begin
  if new.status<>'Approved' or new.date_from is null then
    delete from calendar_events where linked_leave_id=new.id; return new;
  end if;
  select id into pid from personnel where name=new.employee limit 1;
  lbl := case when new.type='Others' and coalesce(new.other_type,'')<>'' then new.other_type else new.type end;
  ed := case when new.date_to is not null and new.date_to>=new.date_from then new.date_to else new.date_from end;
  insert into calendar_events(title,category,start_date,end_date,person_ids,remarks,linked_leave_id,added_by,added_by_name)
  values(coalesce(new.employee,'Personnel')||' — '||coalesce(lbl,'Leave'),'Leave',new.date_from,ed,
         case when pid is null then '{}'::bigint[] else array[pid] end,
         'Auto-synced from approved Leave record. '||coalesce(new.remarks,''),new.id,new.added_by,new.added_by_name)
  on conflict (linked_leave_id) do update set title=excluded.title,start_date=excluded.start_date,
    end_date=excluded.end_date,person_ids=excluded.person_ids,remarks=excluded.remarks;
  return new;
end $$;
create trigger trg_leave_calendar after insert or update on leave_records for each row execute function sync_leave_calendar();

-- ============ row level security ============
alter table profiles enable row level security;
create policy profiles_select on profiles for select to authenticated using (id=auth.uid() or is_admin());
create policy profiles_admin_write on profiles for all to authenticated using (is_admin()) with check (is_admin());

-- standard modules: permission matrix from profiles.permissions; edit/delete limited to the owner (admins: all)
do $$ declare r record; begin
  for r in select * from (values ('attendance','attendance'),('leave_records','leave'),('contacts','contacts'),('memos','memos'),
    ('trainings','trainings'),('email_records','email'),('documentation','documentation'),('calendar_events','calendar')) v(t,tab) loop
    execute format('alter table public.%I enable row level security', r.t);
    execute format('create policy "%1$s_select" on public.%1$I for select to authenticated using (public.has_perm(%2$L,''view''))', r.t, r.tab);
    execute format('create policy "%1$s_insert" on public.%1$I for insert to authenticated with check (public.has_perm(%2$L,''add'') and (added_by=auth.uid() or public.is_admin()))', r.t, r.tab);
    execute format('create policy "%1$s_update" on public.%1$I for update to authenticated using (public.has_perm(%2$L,''edit'') and (added_by=auth.uid() or public.is_admin()))', r.t, r.tab);
    execute format('create policy "%1$s_delete" on public.%1$I for delete to authenticated using (public.has_perm(%2$L,''delete'') and (added_by=auth.uid() or public.is_admin()))', r.t, r.tab);
  end loop;
end $$;

-- calendar: Staff may also edit/delete activities they are tagged on
create policy calendar_tagged_update on calendar_events for update to authenticated
  using (my_role()='Staff' and has_perm('calendar','edit') and exists(select 1 from personnel p where p.user_id=auth.uid() and p.id=any(person_ids)));
create policy calendar_tagged_delete on calendar_events for delete to authenticated
  using (my_role()='Staff' and has_perm('calendar','delete') and exists(select 1 from personnel p where p.user_id=auth.uid() and p.id=any(person_ids)));

-- personnel
alter table personnel enable row level security;
create policy personnel_select on personnel for select to authenticated using (
  has_perm('personnel','view') and (is_admin() or (status<>'Inactive' and
    (user_id is null or exists(select 1 from profiles pr where pr.id=personnel.user_id and pr.active)))));
create policy personnel_insert on personnel for insert to authenticated with check (is_admin());
create policy personnel_delete on personnel for delete to authenticated using (is_admin());
create policy personnel_update on personnel for update to authenticated using (
  is_admin() or (has_perm('personnel','edit') and (user_id=auth.uid() or exists(select 1 from profiles where id=auth.uid() and personnel_scope_all))));

alter table personnel_documents enable row level security;
create policy pdoc_select on personnel_documents for select to authenticated using (has_perm('personnel','view'));
create policy pdoc_write on personnel_documents for all to authenticated using (can_manage_person(personnel_id)) with check (can_manage_person(personnel_id));

alter table personnel_doc_links enable row level security;
create policy plink_select on personnel_doc_links for select to authenticated using (
  is_admin() or exists(select 1 from personnel_documents d join personnel p on p.id=d.personnel_id where d.id=doc_id and p.user_id=auth.uid()));
create policy plink_write on personnel_doc_links for all to authenticated
  using (exists(select 1 from personnel_documents d where d.id=doc_id and can_manage_person(d.personnel_id)))
  with check (exists(select 1 from personnel_documents d where d.id=doc_id and can_manage_person(d.personnel_id)));

-- lookup lists, focal person, funds, settings
alter table doc_types enable row level security;
create policy dt_select on doc_types for select to authenticated using (true);
create policy dt_write on doc_types for all to authenticated using (my_role() in ('Administrator','Staff') and has_perm('documentation','add')) with check (my_role() in ('Administrator','Staff') and has_perm('documentation','add'));

alter table focal_items enable row level security;
create policy focal_select on focal_items for select to authenticated using (has_perm('focal','view'));
create policy focal_write on focal_items for all to authenticated
  using (is_admin() or (my_role()='Staff' and has_perm('focal','add')))
  with check (is_admin() or (my_role()='Staff' and has_perm('focal','add')));

alter table funds enable row level security;
create policy funds_select on funds for select to authenticated using (has_perm('funds','view'));
create policy funds_admin on funds for all to authenticated using (is_admin()) with check (is_admin());
alter table fund_types enable row level security;
create policy ft_select on fund_types for select to authenticated using (has_perm('funds','view'));
create policy ft_admin on fund_types for all to authenticated using (is_admin()) with check (is_admin());

alter table settings enable row level security;
create policy set_select on settings for select to authenticated using (true);
create policy set_admin on settings for all to authenticated using (is_admin()) with check (is_admin());

alter table audit_log enable row level security;
create policy audit_select on audit_log for select to authenticated using (is_admin());
create policy audit_insert on audit_log for insert to authenticated with check (user_id=auth.uid());
alter table trash enable row level security;
create policy trash_admin on trash for select to authenticated using (is_admin());
create policy trash_delete on trash for delete to authenticated using (is_admin());
create policy trash_insert on trash for insert to authenticated with check (my_role() is not null);

-- QR codes: table is admin-only; everyone else gets the role-appropriate image through get_qr_codes()
alter table qr_codes enable row level security;
create policy qr_admin on qr_codes for all to authenticated using (is_admin()) with check (is_admin());

create or replace function public.get_qr_codes() returns table(id bigint,label text,image text,link text)
language sql stable security definer set search_path=public as $$
  select q.id,q.label,
    case when my_role()='Guest' then q.decoy_image else q.real_image end,
    case when my_role()='Guest' then q.decoy_link else q.real_link end
  from qr_codes q where my_role() is not null order by q.id $$;

create or replace function public.clear_must_change_password() returns void language sql security definer set search_path=public as
$$ update profiles set must_change_password=false where id=auth.uid() $$;

-- after a backup restore, move identity sequences past the highest restored id (admin only)
create or replace function public.reset_sequences() returns void language plpgsql security definer set search_path=public as $$
declare t text;
begin
  if not is_admin() then raise exception 'admin only'; end if;
  foreach t in array array['personnel','personnel_documents','attendance','leave_records','calendar_events','contacts','memos','trainings','email_records','documentation','funds','focal_items','qr_codes','audit_log','trash'] loop
    execute format('select setval(pg_get_serial_sequence(''public.%I'',''id''), greatest((select coalesce(max(id),0) from public.%I),1))', t, t);
  end loop;
end $$;

revoke execute on function public.get_qr_codes(), public.clear_must_change_password(), public.reset_sequences() from public, anon;
grant execute on function public.get_qr_codes(), public.clear_must_change_password(), public.reset_sequences() to authenticated;

-- ============ file storage ============
insert into storage.buckets (id,name,public) values ('attachments','attachments',false) on conflict do nothing;
create policy att_select on storage.objects for select to authenticated using (
  bucket_id='attachments' and ((storage.foldername(name))[1]<>'qr-real' or my_role()<>'Guest'));
create policy att_insert on storage.objects for insert to authenticated with check (
  bucket_id='attachments' and my_role() in ('Administrator','Staff')
  and ((storage.foldername(name))[1] not in ('qr-real','qr-decoy') or is_admin()));
create policy att_delete on storage.objects for delete to authenticated using (
  bucket_id='attachments' and (owner=auth.uid() or owner_id=auth.uid()::text or is_admin()));

-- ============ first administrator (run AFTER creating the auth user — see README step 3) ============
-- insert into profiles (id,username,name,role,must_change_password,personnel_scope_all,permissions)
-- select id,'admin','System Administrator','Administrator',false,true,'{}' from auth.users where email='admin@psto.local';
-- insert into personnel (user_id,first_name,status) select id,'System Administrator','Active' from auth.users where email='admin@psto.local';
